title: Howzatt!!
description: An elegant app that displays live cricket score on your mac's menu bar.
google_analytics: UA-59762231-1
show_downloads: true
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
